//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameImage
    {
        public int ImageID { get; set; }
        public int GameID { get; set; }
        public byte[] ImageSource { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
